### ISSUE TITLE
Error when I set an absolute path for the host

### ISSUE THREAD

**Issue by casevanarkel** [FunnelEnvy/optimizely-cli#30]
I keep running into this error when trying to set a path:

optcli host /Users/bsoth/optimizely_local/legal-documents-form/variation_1/

and the error:

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'project.json'

**Comment by johnhenryenvy** [comment]
Hi,
The command line interface creates a structure like this:

/<project folder>
  project.json
  /<experiment folder>
    ...
    /<variation folder>
      ...

I'm wondering:
a) did you create your project using optcil init, optcli experiment, and optcli variation?
b) is there a project.json file located in the directory  "/Users/bsoth/optimizely_local/"?

If the answer is yes to both of those, then this is definitely our issue and we'll push out a fix soon.
If the answer is no, then we can do a much better job at documenting this project and we'll push out a fix soon.

Thanks for contributing!

**Comment by krazyken04** [comment]
I'm actually running into the same thing, but not doing anything special. Friday I was able to get this working, but today it's not :\

a) I did create it with all the above (even tried an old experiment and variation that worked). 
b) there is a project.json file

Here's the terminal output: 

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'project.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.module.exports.loadConfigItem (/usr/local/lib/node_modules/optimizely-cli/lib/file-util.js:25:10)
    at Project.OptCLIBase.loadFromFile (/usr/local/lib/node_modules/optimizely-cli/lib/optcli-base.js:30:30)
    at new LocalController (/usr/local/lib/node_modules/optimizely-cli/lib/server/controller.js:21:16)
    at module.exports (/usr/local/lib/node_modules/optimizely-cli/lib/commands/host.js:40:21)
    at Command.<anonymous> (/usr/local/lib/node_modules/optimizely-cli/bin/optcli.js:13:8)
    at Command.listener (/usr/local/lib/node_modules/optimizely-cli/node_modules/commander/index.js:289:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/optimizely-cli/node_modules/commander/index.js:572:12)
    at Command.parse (/usr/local/lib/node_modules/optimizely-cli/node_modules/commander/index.js:438:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/optimizely-cli/bin/optcli.js:71:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by krazyken04** [comment]
Just a heads up, I was able to get this working again by doing the init with the -r option pointing to the existing project. Despite all project files being their already, hosting now works again. 

Very odd though that it stopped working. Anyways, here's the command:

    optcli init -r [[exisitng project id]]

You can get your project ID after logging in to optimizely and going to your optimizely project dashboard:

    https://www.optimizely.com/projects/[[your_project_id]]/experiments

Back to going way too fast with optimizely! :D

**Comment by axs89** [comment]
Great to hear that you got it working, thanks for leaving the feedback. We'll take a closer look at it.

**Comment by nselvidge** [comment]
This should be addressed in v0.15.1
